runtime: python
env: flex
entrypoint: waitress-serve --port=8080 superscript:app

runtime_config:
  python_version: 3

api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: superscript.app

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10